# Generated by Django 5.1.1 on 2025-02-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='conditionX',
            field=models.CharField(default='50%', max_length=255),
        ),
        migrations.AddField(
            model_name='category',
            name='conditionY',
            field=models.CharField(default='50%', max_length=255),
        ),
    ]
