# Generated by Django 5.1.1 on 2025-06-01 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_head',
            field=models.BooleanField(default=False, verbose_name='Главная категория'),
        ),
    ]
