# Generated by Django 5.1.1 on 2025-03-21 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parentMas',
            field=models.ManyToManyField(blank=True, related_name='childrenMas', to='api.category'),
        ),
    ]
