# Generated by Django 5.1.1 on 2024-09-19 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_name', models.CharField(max_length=255)),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='api.category')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='all_categories',
            field=models.ManyToManyField(related_name='projects', to='api.category', verbose_name='Все категории'),
        ),
        migrations.AddField(
            model_name='project',
            name='head_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_projects', to='api.category', verbose_name='Голова категорий'),
        ),
    ]
