# Generated by Django 5.1.1 on 2024-09-20 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_project_all_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='all_categories',
        ),
    ]
