# Generated by Django 5.1.1 on 2025-02-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_conditionx_category_conditiony'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='rgb(0, 0, 0)', max_length=255),
        ),
    ]
