# Generated by Django 5.1.1 on 2024-11-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='condition',
            field=models.BooleanField(default=True),
        ),
    ]
